name: First Workflow

on:
  push:
    branches: ['pizza']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - if: ${{ github.event.workflow_run.conclusion == 'success' }}
          run: "echo YAY"
