name: Second Workflow

on:
    workflow_run:
        workflows:
        - 'First Workflow'
        branches:
        - main
        - pizza
        types:
        - completed
    
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.event.workflow_run.head_branch }}
            - run: echo "Hi from pizza"
              if: ${{ github.event.workflow_run.head_branch }} == "pizza"
