name: Second Workflow

on:
    workflow_run:
        workflows:
        - 'First Workflow'
        branches:
        - main
        - pizza
        types:
        - completed

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
