name: Second Workflow

on:
    workflow_run:
        workflows:
        - 'First Workflow'
        branches:
        - main
        - pizza
        types:
        - completed

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - run: "echo ${{ github.ref_name }}"
